### ISSUE TITLE
Any topicref seems to have "processing-role='resource-only'" set as default attribute value in the DTDs

### ISSUE THREAD

**Issue by raducoravu** [oasis-tcs/dita-lwdita#16]
In the "org.oasis.xdita/dtd/lw-map.mod" for a topicref the default processing-role value seems to be resource-only which is probably not what would be expected.

**Comment by carlosevia** [comment]
I added an entity for processing and will build a new release. Thank you

**Comment by raducoravu** [comment]
👍
