### ISSUE TITLE
lwdita hdita files have incorrect markup

### ISSUE THREAD

**Issue by markgif** [oasis-tcs/dita-lwdita#22]
The sample HDITA files under here:

https://github.com/oasis-tcs/dita-lwdita/tree/master/org.oasis-open.xdita/samples/hdita

have no root `<html>` element, and the `<title>` element needs to be a child of `<head>`. These are basic HTML5 tags, even though a browser will display it without them. And a `<body>` tag is usual also.

**Comment by carlosevia** [comment]
Fixed and will be in new release
