### ISSUE TITLE
desc element in HDITA

### ISSUE THREAD

**Issue by ccheraa** [oasis-tcs/dita-lwdita#44]
According to the `lw-topic.dtd`, the element `desc` can be a child of `audio`, `video`, or `fig`, but this document ,[LwDITA-v1.0-cnprd01.html](http://docs.oasis-open.org/dita/LwDITA/v1.0/cnprd01/LwDITA-v1.0-cnprd01.html), says that "desc" should be represented in HDITA as:
- `caption` if it's a child of `table`
- `figcaption` if it's a child of `fig`

This document doesn't mention how to represent it when it's a child of `video`/`audio`, also it implies that it can be a child of `table` (`simpletable`), which is not mentioned in `lw-topic.dtd`.

**Comment by carlosevia** [comment]
Thank you very much for the observation. `audio`, `video`, and `simpletable` are evolving to reflect forthcoming changes in the DITA 2.0 spec. The LwDITA spec will also address these changes.
