### ISSUE TITLE
<fn> element in <body>?

### ISSUE THREAD

**Issue by coldcaz** [oasis-tcs/dita-lwdita#46]
The lw-dita dtd allows the `<fn>` element within the `<body>`.
However, this seems to be invalid DITA: http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part2-tech-content/contentmodels/cmtcb.html#cmtcb__body

DITA 1.3 treats the `<fn>` tag as an inline element. 

Hence it seems like LW-DITA is not compatible to DITA 1.3, or am I missing something?

**Comment by carlosevia** [comment]
Thanks for pointing this out. The design of <fn> in XDITA has a complicated history. We will address this in our next LwDITA subcommittee meeting and I will report back.

**Comment by coldcaz** [comment]
Hi @carlosevia,

thanks for your response! Looking forward to your feedback.

**Comment by carlosevia** [comment]
I have updated the grammar files in the spec branch to include a new behavior for <fn>, which now requires a parent <div>. In XDITA, <div> will only be allowed as a container for <fn>. Please let me know if it works. I plan to make a new release once we clean a few more files.
