### ISSUE TITLE
Fix broken "catalog-dita.xml" mappings

### ISSUE THREAD

**Issue by raducoravu** [oasis-tcs/dita-lwdita#9]
Open plugin's "catalog-dita.xml" and replace all occurrences of:

dtd/topic.mod => dtd/lw-topic.mod
dtd/topic.dtd => dtd/lw-topic.dtd
dtd/map.dtd => dtd/lw-map.dtd
dtd/map.mod => dtd/lw-map.mod

**Comment by carlosevia** [comment]
Fixed by @keberlein Mar 1, 2018

**Comment by raducoravu** [comment]
BTW, when creating new DITA topics and maps what are the "official" public IDs now?
These ones:
-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN
-//OASIS//DTD LIGHTWEIGHT DITA Map//EN
?

Or do you plan to also change these in time as the standard work progresses?

**Comment by carlosevia** [comment]
We do not foresee any changes in the public IDs for XDITA map and topic.
